### PR TITLE
Run one sample

### PR DESCRIPTION
**Pull request by joverlee521**
This PR includes changes from both #7 and #8.

1. Edits the `setup_config_file` script to create new config files rather than overwrite the template.
2. Adds a template for one sample/target configs: `one-sample-template.json`
3. Adds script `setup_config_for_one_sample_target_pair.py` to create config files for one sample/target pair. 
4. Adds `Snakefile_one_sample` specific for one sample/target pairs since there are steps in the pipeline that are unnecessary when the pipeline is provided the specific sample and target.

### CODE REVIEW

**Comment by joverlee521** [comment]
[Tweak assembly pipeline to easily run a single (sample, organism) combination](https://trello.com/c/b7wuWUkC/170-tweak-assembly-pipeline-to-easily-run-a-single-sample-organism-combination)

**Comment by kairstenfay** [comment]
Thanks so much for creating a template config file that doesn't get overwritten! 

I haven't gone through this PR yet but I noticed your comment about creating a second Snakefile because not all rules apply when running only one sample.
Instead of creating a second Snakefile, have you considered using a [Snakemake sub-workflow](https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#sub-workflows)?

**Review by kairstenfay — CHANGES_REQUESTED** [review]
I am still very hesitant to have two separate Snakefiles when we're only changing the number of samples being run. I think this will be very frustrating to maintain when we make changes to the Snakefile.

**Comment by tsibley** [comment]
I haven't looked at this in depth yet, but I skimmed it briefly and agree with @kairstenfay that two Snakefiles that are very similar makes me very wary. Is it overly difficult to make one Snakefile with more conditionals? I wonder if we could take a step back and reconsider how the workflow is put together without dramatically increasing effort here. I know we've talked a little about why this is hard, but unfortunately I'm not remembering the details. Perhaps we could all discuss in person and figure out the best way forward?

**Comment by joverlee521** [comment]
Combined with #12 into one PR #14

**Comment by tsibley** [comment]
[Tweak assembly pipeline to easily run a single (sample, organism) combination](https://trello.com/c/b7wuWUkC/170-tweak-assembly-pipeline-to-easily-run-a-single-sample-organism-combination)

**Pull request closed without merging**
