### PR TITLE
Run one snakefile plus report not mapped

### PR DESCRIPTION
**Pull request by kairstenfay**
Hey Jover, I just rebased the branch `report-not-mapped` onto the updated `run_one_sample` . Can you verify that everything looks ok and close PRs #10 and #12 ? This will make reviewing easier. Thank you!

### CODE REVIEW

**Comment by kairstenfay** [comment]
Hmm, these might also need to be rebased onto master. I tried doing it myself but I am afraid of losing your work.

**Comment by joverlee521** [comment]
Thanks @kairstenfay for merging the two PRs. I did some clean up and rebased on to master.

**Comment by joverlee521** [comment]
> I am still very hesitant to have two separate Snakefiles when we're only changing the number of samples being run. I think this will be very frustrating to maintain when we make changes to the Snakefile.

>I haven't looked at this in depth yet, but I skimmed it briefly and agree with @kairstenfay that two Snakefiles that are very similar makes me very wary. Is it overly difficult to make one Snakefile with more conditionals?

I think I originally made a second Snakefile with the thought that we would eventually deprecate/delete the original batch Snakefile, but i can definitely spend some time on combining the two

**Comment by tsibley** [comment]
> I think I originally made a second Snakefile with the thought that we would eventually deprecate/delete the original batch Snakefile, but i can definitely spend some time on combining the two

Ohhhh, that makes a lot of sense. I'm definitely ok with that choice if we prioritize deleting the original batch Snakefile. :-)

**Comment by kairstenfay** [comment]
Same here

**Comment by tsibley** [comment]
[Update sequence read set details to reflect a failed assembly job](https://trello.com/c/V67HmpJv/179-update-sequence-read-set-details-to-reflect-a-failed-assembly-job)

**Comment by tsibley** [comment]
[Tweak assembly pipeline to easily run a single (sample, organism) combination](https://trello.com/c/b7wuWUkC/170-tweak-assembly-pipeline-to-easily-run-a-single-sample-organism-combination)

**Comment by kairstenfay** [comment]
@joverlee521  Has this effectively become the master branch? If so, I think we should close this PR and merge the branch.

**Comment by joverlee521** [comment]
> @joverlee521 Has this effectively become the master branch? If so, I think we should close this PR and merge the branch.

It hast not, I only cherry-picked the first commit in this PR. The rest still needs to be merged.

**Comment by joverlee521** [comment]
I rebased on to master and incorporated all of our most recent changes in assembly

**Comment by kairstenfay** [comment]
Has this effectively become the master branch for seattleflu assembly? If so, I think we should merge this as-is.

**Comment by joverlee521** [comment]
> Has this effectively become the master branch for seattleflu assembly? If so, I think we should merge this as-is.

No, it has not. I'm still running things via the master branch.

**Comment by joverlee521** [comment]
Closing since we are no longer actively running assembly pipeline. Keeping the branch in case it's needed in the future.

**Pull request closed without merging**
